// web-next/src/app/proxy/page.tsx
"use client";

import { useState, useEffect } from "react";
import { getModels, getProxyInfo, reloadProviders, fetchJSON, postJSON, type Model } from "@/lib/api";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function ProxyPage() {
  const [models, setModels] = useState<Model[]>([]);
  const [reloadMsg, setReloadMsg] = useState("");
  const [costs, setCosts] = useState<Record<string, unknown>>({});
  const [cache, setCache] = useState<Record<string, unknown>>({});
  const [vkeys, setVkeys] = useState<Array<Record<string, unknown>>>([]);
  const [newKeyName, setNewKeyName] = useState("");
  const [newKeyLimit, setNewKeyLimit] = useState(1000);
  const [createdKey, setCreatedKey] = useState("");

  useEffect(() => {
    Promise.all([getProxyInfo(), getModels(), fetchJSON("/v1/costs"), fetchJSON("/v1/cache"), fetchJSON("/v1/virtual-keys")])
      .then(([, m, c, ch, vk]) => {
        if (m) setModels((m as { data: Model[] }).data || []);
        if (c) setCosts(c as Record<string, unknown>);
        if (ch) setCache(ch as Record<string, unknown>);
        if (vk) setVkeys((vk as { keys: Array<Record<string, unknown>> }).keys || []);
      });
  }, []);

  const doReload = async () => {
    setReloadMsg("⏳ กำลัง reload...");
    const r = await reloadProviders();
    setReloadMsg(r ? `✅ Reload สำเร็จ! (${(r as { providers?: number }).providers} providers)` : "❌ ล้มเหลว");
    setTimeout(() => setReloadMsg(""), 3000);
  };

  const doClearCache = async () => {
    await postJSON("/v1/cache/clear");
    const c = await fetchJSON("/v1/cache");
    if (c) setCache(c as Record<string, unknown>);
  };

  const createVKey = async () => {
    if (!newKeyName.trim()) return;
    const r = await postJSON("/v1/virtual-keys", { action: "create", name: newKeyName, daily_limit: newKeyLimit }) as Record<string, unknown>;
    if (r?.key) {
      setCreatedKey(r.key as string);
      setNewKeyName("");
      const vk = await fetchJSON("/v1/virtual-keys");
      if (vk) setVkeys((vk as { keys: Array<Record<string, unknown>> }).keys || []);
    }
  };

  const deleteVKey = async (id: string) => {
    await postJSON("/v1/virtual-keys", { action: "delete", id });
    const vk = await fetchJSON("/v1/virtual-keys");
    if (vk) setVkeys((vk as { keys: Array<Record<string, unknown>> }).keys || []);
  };

  const total = (costs.total || {}) as Record<string, unknown>;
  const byProvider = (costs.by_provider || {}) as Record<string, Record<string, unknown>>;

  return (
    <>
      <div className="space-y-6">
        {/* Connection Guide */}
        <div>
          <h3 className="text-lg font-bold mb-3">🔌 วิธีเชื่อมต่อ Proxy</h3>
          <p className="text-sm text-muted-foreground mb-4">ใช้ได้กับทุกแอปที่รองรับ OpenAI API — แค่เปลี่ยน Base URL</p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {[
              { title: "🦞 OpenClaw", lang: "env", code: `OPENAI_API_BASE=https://airouter.satistang.com/v1\nOPENAI_API_KEY=any\nMODEL_NAME=auto` },
              { title: "🐍 Python (OpenAI SDK)", lang: "python", code: `from openai import OpenAI\n\nclient = OpenAI(\n    base_url="https://airouter.satistang.com/v1",\n    api_key="any"\n)\n\nres = client.chat.completions.create(\n    model="auto",\n    messages=[{"role": "user", "content": "สวัสดี"}]\n)\nprint(res.choices[0].message.content)` },
              { title: "🟢 Node.js", lang: "javascript", code: `import OpenAI from "openai";\n\nconst client = new OpenAI({\n  baseURL: "https://airouter.satistang.com/v1",\n  apiKey: "any"\n});\n\nconst res = await client.chat.completions.create({\n  model: "auto",\n  messages: [{ role: "user", content: "สวัสดี" }]\n});\nconsole.log(res.choices[0].message.content);` },
              { title: "📟 cURL", lang: "bash", code: `curl -X POST https://airouter.satistang.com/v1/chat/completions \\\n  -H "Content-Type: application/json" \\\n  -H "Authorization: Bearer any" \\\n  -d '{\n    "model": "auto",\n    "messages": [{"role": "user", "content": "สวัสดี"}]\n  }'` },
            ].map(ex => (
              <Card key={ex.title} className="border-[var(--clr-green)]/30">
                <CardContent className="p-4">
                  <div className="flex items-center justify-between mb-2">
                    <span className="font-bold text-sm">{ex.title}</span>
                    <Button variant="outline" size="sm" className="text-xs h-6"
                      onClick={() => navigator.clipboard.writeText(ex.code)}>
                      📋 Copy
                    </Button>
                  </div>
                  <pre className="p-3 rounded-lg text-xs font-mono bg-secondary overflow-x-auto whitespace-pre-wrap">{ex.code}</pre>
                </CardContent>
              </Card>
            ))}
          </div>
          <Card className="mt-4 bg-secondary/30">
            <CardContent className="p-4">
              <h4 className="font-bold text-sm mb-2">💡 Model Format</h4>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-2 text-xs font-mono">
                <div><span className="text-[var(--clr-green)] font-bold">auto</span> → เลือก provider ดีที่สุดอัตโนมัติ</div>
                <div><span className="text-[var(--clr-accent)] font-bold">groq/llama-3.3-70b-versatile</span> → เจาะจง provider + model</div>
                <div><span className="text-[var(--clr-purple)] font-bold">llama-3.3-70b-versatile</span> → หา provider ที่มี model นี้</div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Cost Tracking */}
        <div>
          <h3 className="text-lg font-bold mb-3">💰 Cost Tracking</h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3">
            {[
              { label: "Total Requests", value: (total.requests as number) || 0, color: "text-[var(--clr-accent)]" },
              { label: "Total Tokens", value: ((total.tokens as Record<string, number>)?.total || 0).toLocaleString(), color: "text-[var(--clr-purple)]" },
              { label: "ถ้าจ่ายจริง (USD)", value: `$${total.cost_usd || "0.00"}`, color: "text-[var(--clr-green)]" },
              { label: "ถ้าจ่ายจริง (THB)", value: `฿${total.cost_thb || "0.00"}`, color: "text-[var(--clr-yellow)]" },
            ].map(s => (
              <Card key={s.label}>
                <CardContent className="p-4">
                  <div className="text-xs text-muted-foreground mb-1">{s.label}</div>
                  <div className={`text-2xl font-bold ${s.color}`}>{s.value}</div>
                </CardContent>
              </Card>
            ))}
          </div>

          {Object.keys(byProvider).length > 0 && (
            <Card>
              <CardContent className="p-0">
                <table className="w-full text-sm">
                  <thead><tr className="bg-secondary/50">
                    <th className="text-left px-3 py-2 text-xs text-muted-foreground">Provider</th>
                    <th className="text-right px-3 py-2 text-xs text-muted-foreground">Requests</th>
                    <th className="text-right px-3 py-2 text-xs text-muted-foreground">Tokens</th>
                    <th className="text-right px-3 py-2 text-xs text-muted-foreground">Avg Latency</th>
                    <th className="text-right px-3 py-2 text-xs text-muted-foreground">Cost (USD)</th>
                  </tr></thead>
                  <tbody className="divide-y divide-border">
                    {Object.entries(byProvider).map(([pid, d]) => (
                      <tr key={pid}>
                        <td className="px-3 py-2 font-semibold">{pid}</td>
                        <td className="px-3 py-2 text-right font-mono">{d.requests as number}</td>
                        <td className="px-3 py-2 text-right font-mono">{(d.tokens as number)?.toLocaleString()}</td>
                        <td className="px-3 py-2 text-right font-mono text-[var(--clr-accent)]">{d.avg_latency as number}ms</td>
                        <td className="px-3 py-2 text-right font-mono text-[var(--clr-green)]">${d.cost_usd as string}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </CardContent>
            </Card>
          )}
        </div>

        {/* Cache */}
        <div>
          <div className="flex items-center justify-between mb-3">
            <h3 className="text-lg font-bold">⚡ Semantic Cache</h3>
            <Button variant="destructive" size="sm" onClick={doClearCache}>🗑️ ล้าง Cache</Button>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {[
              { label: "Cached Items", value: (cache.total_cached as number) || 0, color: "text-[var(--clr-accent)]" },
              { label: "Hit Rate", value: `${(cache.hit_rate as number) || 0}%`, color: "text-[var(--clr-green)]" },
              { label: "Cache Hits", value: (cache.hits as number) || 0, color: "text-[var(--clr-purple)]" },
              { label: "Time Saved", value: `${(((cache.saved_ms as number) || 0) / 1000).toFixed(1)}s`, color: "text-[var(--clr-yellow)]" },
            ].map(s => (
              <Card key={s.label}>
                <CardContent className="p-4">
                  <div className="text-xs text-muted-foreground mb-1">{s.label}</div>
                  <div className={`text-2xl font-bold ${s.color}`}>{s.value}</div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Virtual Keys */}
        <div>
          <h3 className="text-lg font-bold mb-3">🔑 Virtual API Keys</h3>
          <div className="flex gap-2 mb-3">
            <Input value={newKeyName} onChange={e => setNewKeyName(e.target.value)}
              placeholder="ชื่อ key (เช่น openclaw, app-test)" className="flex-1" />
            <Input type="number" value={newKeyLimit} onChange={e => setNewKeyLimit(Number(e.target.value))}
              className="w-24" />
            <Button onClick={createVKey}>+ สร้าง Key</Button>
          </div>
          {createdKey && (
            <Card className="mb-3 border-[var(--clr-green)] bg-[var(--clr-green)]/5">
              <CardContent className="p-3">
                <span className="text-xs font-bold text-[var(--clr-green)]">🔑 Key ใหม่ (copy แล้วเก็บไว้):</span>
                <div className="flex items-center gap-2 mt-1">
                  <code className="text-sm font-mono flex-1 p-2 rounded bg-secondary">{createdKey}</code>
                  <Button size="sm" onClick={() => { navigator.clipboard.writeText(createdKey); setCreatedKey(""); }}>📋 Copy</Button>
                </div>
              </CardContent>
            </Card>
          )}
          {vkeys.length > 0 ? (
            <Card>
              <CardContent className="p-0">
                <table className="w-full text-sm">
                  <thead><tr className="bg-secondary/50">
                    <th className="text-left px-3 py-2 text-xs text-muted-foreground">Name</th>
                    <th className="text-left px-3 py-2 text-xs text-muted-foreground">Key</th>
                    <th className="text-right px-3 py-2 text-xs text-muted-foreground">Limit</th>
                    <th className="text-right px-3 py-2 text-xs text-muted-foreground">Used</th>
                    <th className="text-center px-3 py-2 text-xs text-muted-foreground">Actions</th>
                  </tr></thead>
                  <tbody className="divide-y divide-border">
                    {vkeys.map((vk, i) => (
                      <tr key={i}>
                        <td className="px-3 py-2 font-semibold">{vk.name as string}</td>
                        <td className="px-3 py-2 font-mono text-xs text-muted-foreground">{vk.key_preview as string}</td>
                        <td className="px-3 py-2 text-right">{vk.daily_limit as number}/day</td>
                        <td className="px-3 py-2 text-right font-mono text-[var(--clr-accent)]">{((vk.usage as Record<string, number>)?.today_requests) || 0}</td>
                        <td className="px-3 py-2 text-center">
                          <Button variant="ghost" size="sm" className="text-[var(--clr-red)]" onClick={() => deleteVKey(vk.id as string)}>🗑️</Button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </CardContent>
            </Card>
          ) : (
            <Card><CardContent className="py-6 text-center text-muted-foreground">ยังไม่มี Virtual Key — สร้างเพื่อแจกให้แอปหรือ user</CardContent></Card>
          )}
        </div>

        {/* Models */}
        <div>
          <div className="flex items-center gap-3 mb-3">
            <h3 className="text-lg font-semibold">📖 โมเดลทั้งหมด ({models.length})</h3>
            <Button variant="outline" size="sm" onClick={doReload}>🔄 Reload</Button>
            {reloadMsg && <span className="text-sm font-semibold text-[var(--clr-green)]">{reloadMsg}</span>}
          </div>
          <Card>
            <CardContent className="p-0">
              <table className="w-full text-sm">
                <thead><tr className="bg-secondary/50">
                  <th className="text-left px-4 py-2 text-xs text-muted-foreground">Model ID</th>
                  <th className="text-left px-4 py-2 text-xs text-muted-foreground">Provider</th>
                </tr></thead>
                <tbody className="divide-y divide-border">
                  {models.map((m, i) => (
                    <tr key={i}>
                      <td className="px-4 py-2 font-mono text-xs text-[var(--clr-accent)]">{m.id}</td>
                      <td className="px-4 py-2">{m.owned_by}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </CardContent>
          </Card>
        </div>
      </div>
    </>
  );
}

// web/src/routes/proxy/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { getModels, getProxyInfo, reloadProviders, fetchJSON, postJSON } from '$lib/api';
	let info = $state<any>({});
	let models = $state<any[]>([]);
	let reloadMsg = $state('');
	let costs = $state<any>({});
	let cache = $state<any>({});
	let vkeys = $state<any[]>([]);
	let newKeyName = $state('');
	let newKeyLimit = $state(1000);
	let createdKey = $state('');

	onMount(async () => {
		const [i, m, c, ch, vk] = await Promise.all([
			getProxyInfo(), getModels(),
			fetchJSON('/v1/costs'), fetchJSON('/v1/cache'), fetchJSON('/v1/virtual-keys'),
		]);
		info = i || {};
		if (m?.data) models = m.data;
		costs = c || {};
		cache = ch || {};
		vkeys = vk?.keys || [];
	});

	async function doReload() {
		reloadMsg = '⏳ กำลัง reload...';
		const r = await reloadProviders();
		reloadMsg = r ? `✅ Reload สำเร็จ! (${r.providers} providers)` : '❌ ล้มเหลว';
		setTimeout(() => reloadMsg = '', 3000);
	}

	async function clearCache() {
		await postJSON('/v1/cache/clear');
		cache = await fetchJSON('/v1/cache') || {};
	}

	async function createVKey() {
		if (!newKeyName.trim()) return;
		const r = await postJSON('/v1/virtual-keys', {
			action: 'create', name: newKeyName, daily_limit: newKeyLimit,
		});
		if (r?.key) {
			createdKey = r.key;
			newKeyName = '';
			vkeys = (await fetchJSON('/v1/virtual-keys'))?.keys || [];
		}
	}

	async function deleteVKey(id: string) {
		await postJSON('/v1/virtual-keys', { action: 'delete', id });
		vkeys = (await fetchJSON('/v1/virtual-keys'))?.keys || [];
	}

	async function refreshData() {
		const [c, ch] = await Promise.all([fetchJSON('/v1/costs'), fetchJSON('/v1/cache')]);
		costs = c || {};
		cache = ch || {};
	}
</script>

<div class="space-y-6">

<!-- OpenClaw Config -->
<div class="p-5 rounded-xl border" style="background: var(--bg2); border-color: var(--green); border-left: 4px solid var(--green);">
	<h3 class="text-lg font-bold mb-3" style="color: var(--green);">🔌 ตั้งค่า OpenClaw / แอปอื่น</h3>
	<pre class="p-4 rounded-lg text-sm font-mono" style="background: var(--bg3); color: var(--text);">OPENAI_API_BASE=http://127.0.0.1:8900/v1
OPENAI_API_KEY=any
MODEL_NAME=auto</pre>
	<button onclick={() => navigator.clipboard.writeText('OPENAI_API_BASE=http://127.0.0.1:8900/v1\nOPENAI_API_KEY=any\nMODEL_NAME=auto')}
		class="mt-3 px-4 py-2 rounded-lg text-sm font-semibold cursor-pointer" style="background: var(--accent); color: white;">📋 Copy</button>
</div>

<!-- Cost Overview -->
<div>
	<div class="flex items-center justify-between mb-3">
		<h3 class="text-lg font-bold">💰 Cost Tracking</h3>
		<button onclick={refreshData} class="px-3 py-1 rounded text-xs cursor-pointer border" style="border-color: var(--border); color: var(--text2);">🔄 Refresh</button>
	</div>
	<div class="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3">
		<div class="p-4 rounded-xl border" style="background: var(--bg2); border-color: var(--border);">
			<div class="text-xs mb-1" style="color: var(--text2);">Total Requests</div>
			<div class="text-2xl font-bold" style="color: var(--accent);">{costs.total?.requests || 0}</div>
		</div>
		<div class="p-4 rounded-xl border" style="background: var(--bg2); border-color: var(--border);">
			<div class="text-xs mb-1" style="color: var(--text2);">Total Tokens</div>
			<div class="text-2xl font-bold" style="color: var(--purple);">{(costs.total?.tokens?.total || 0).toLocaleString()}</div>
		</div>
		<div class="p-4 rounded-xl border" style="background: var(--bg2); border-color: var(--border);">
			<div class="text-xs mb-1" style="color: var(--text2);">ถ้าจ่ายจริง (USD)</div>
			<div class="text-2xl font-bold" style="color: var(--green);">${costs.total?.cost_usd || '0.00'}</div>
		</div>
		<div class="p-4 rounded-xl border" style="background: var(--bg2); border-color: var(--border);">
			<div class="text-xs mb-1" style="color: var(--text2);">ถ้าจ่ายจริง (THB)</div>
			<div class="text-2xl font-bold" style="color: var(--yellow);">฿{costs.total?.cost_thb || '0.00'}</div>
		</div>
	</div>
	<div class="text-xs" style="color: var(--text3);">💡 {costs.savings_note || 'ใช้ free tier — ตัวเลขเป็น estimate'}</div>

	<!-- By Provider -->
	{#if costs.by_provider && Object.keys(costs.by_provider).length > 0}
	<div class="mt-3 rounded-xl border overflow-hidden" style="background: var(--bg2); border-color: var(--border);">
		<table class="w-full text-sm">
			<thead><tr style="background: var(--bg3);">
				<th class="text-left px-3 py-2 text-xs" style="color: var(--text2);">Provider</th>
				<th class="text-right px-3 py-2 text-xs" style="color: var(--text2);">Requests</th>
				<th class="text-right px-3 py-2 text-xs" style="color: var(--text2);">Tokens</th>
				<th class="text-right px-3 py-2 text-xs" style="color: var(--text2);">Avg Latency</th>
				<th class="text-right px-3 py-2 text-xs" style="color: var(--text2);">Cost (USD)</th>
			</tr></thead>
			<tbody>
				{#each Object.entries(costs.by_provider) as [pid, data]}
					<tr class="border-t" style="border-color: var(--border);">
						<td class="px-3 py-2 font-semibold">{pid}</td>
						<td class="px-3 py-2 text-right font-mono">{data.requests}</td>
						<td class="px-3 py-2 text-right font-mono">{data.tokens?.toLocaleString()}</td>
						<td class="px-3 py-2 text-right font-mono" style="color: var(--accent);">{data.avg_latency}ms</td>
						<td class="px-3 py-2 text-right font-mono" style="color: var(--green);">${data.cost_usd}</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
	{/if}
</div>

<!-- Semantic Cache -->
<div>
	<div class="flex items-center justify-between mb-3">
		<h3 class="text-lg font-bold">⚡ Semantic Cache</h3>
		<button onclick={clearCache} class="px-3 py-1 rounded text-xs cursor-pointer" style="background: var(--red); color: white;">🗑️ ล้าง Cache</button>
	</div>
	<div class="grid grid-cols-2 md:grid-cols-4 gap-3">
		<div class="p-4 rounded-xl border" style="background: var(--bg2); border-color: var(--border);">
			<div class="text-xs mb-1" style="color: var(--text2);">Cached Items</div>
			<div class="text-2xl font-bold" style="color: var(--accent);">{cache.total_cached || 0}</div>
		</div>
		<div class="p-4 rounded-xl border" style="background: var(--bg2); border-color: var(--border);">
			<div class="text-xs mb-1" style="color: var(--text2);">Hit Rate</div>
			<div class="text-2xl font-bold" style="color: var(--green);">{cache.hit_rate || 0}%</div>
		</div>
		<div class="p-4 rounded-xl border" style="background: var(--bg2); border-color: var(--border);">
			<div class="text-xs mb-1" style="color: var(--text2);">Cache Hits</div>
			<div class="text-2xl font-bold" style="color: var(--purple);">{cache.hits || 0}</div>
		</div>
		<div class="p-4 rounded-xl border" style="background: var(--bg2); border-color: var(--border);">
			<div class="text-xs mb-1" style="color: var(--text2);">Time Saved</div>
			<div class="text-2xl font-bold" style="color: var(--yellow);">{((cache.saved_ms || 0) / 1000).toFixed(1)}s</div>
		</div>
	</div>
</div>

<!-- Virtual Keys -->
<div>
	<h3 class="text-lg font-bold mb-3">🔑 Virtual API Keys</h3>
	<div class="flex gap-2 mb-3">
		<input type="text" bind:value={newKeyName} placeholder="ชื่อ key (เช่น openclaw, app-test)"
			class="flex-1 px-3 py-2 rounded-lg border text-sm" style="background: var(--bg); border-color: var(--border); color: var(--text);">
		<input type="number" bind:value={newKeyLimit} class="w-24 px-3 py-2 rounded-lg border text-sm" style="background: var(--bg); border-color: var(--border); color: var(--text);">
		<button onclick={createVKey} class="px-4 py-2 rounded-lg text-sm font-bold text-white cursor-pointer" style="background: var(--accent);">+ สร้าง Key</button>
	</div>

	{#if createdKey}
	<div class="p-3 rounded-lg mb-3 border" style="background: rgba(63,185,80,0.1); border-color: var(--green);">
		<span class="text-xs font-bold" style="color: var(--green);">🔑 Key ใหม่ (copy แล้วเก็บไว้ — จะแสดงครั้งเดียว):</span>
		<div class="flex items-center gap-2 mt-1">
			<code class="text-sm font-mono flex-1 p-2 rounded" style="background: var(--bg3);">{createdKey}</code>
			<button onclick={() => { navigator.clipboard.writeText(createdKey); createdKey = ''; }}
				class="px-3 py-1 rounded text-xs cursor-pointer" style="background: var(--accent); color: white;">📋 Copy</button>
		</div>
	</div>
	{/if}

	{#if vkeys.length > 0}
	<div class="rounded-xl border overflow-hidden" style="background: var(--bg2); border-color: var(--border);">
		<table class="w-full text-sm">
			<thead><tr style="background: var(--bg3);">
				<th class="text-left px-3 py-2 text-xs" style="color: var(--text2);">Name</th>
				<th class="text-left px-3 py-2 text-xs" style="color: var(--text2);">Key</th>
				<th class="text-right px-3 py-2 text-xs" style="color: var(--text2);">Limit</th>
				<th class="text-right px-3 py-2 text-xs" style="color: var(--text2);">Used Today</th>
				<th class="text-right px-3 py-2 text-xs" style="color: var(--text2);">Total</th>
				<th class="text-center px-3 py-2 text-xs" style="color: var(--text2);">Actions</th>
			</tr></thead>
			<tbody>
				{#each vkeys as vk}
				<tr class="border-t" style="border-color: var(--border);">
					<td class="px-3 py-2 font-semibold">{vk.name}</td>
					<td class="px-3 py-2 font-mono text-xs" style="color: var(--text3);">{vk.key_preview}</td>
					<td class="px-3 py-2 text-right">{vk.daily_limit}/day</td>
					<td class="px-3 py-2 text-right font-mono" style="color: var(--accent);">{vk.usage?.today_requests || 0}</td>
					<td class="px-3 py-2 text-right font-mono">{vk.usage?.total_requests || 0}</td>
					<td class="px-3 py-2 text-center">
						<button onclick={() => deleteVKey(vk.id)} class="px-2 py-1 rounded text-xs cursor-pointer" style="color: var(--red);">🗑️</button>
					</td>
				</tr>
				{/each}
			</tbody>
		</table>
	</div>
	{:else}
	<div class="text-center py-6 rounded-xl border" style="background: var(--bg2); border-color: var(--border); color: var(--text2);">
		ยังไม่มี Virtual Key — สร้างเพื่อแจกให้แอปหรือ user แต่ละคน
	</div>
	{/if}
</div>

<!-- Models -->
<div>
	<h3 class="text-lg font-semibold mb-3">📖 โมเดลทั้งหมด ({models.length})</h3>
	<button onclick={doReload} class="mb-3 px-4 py-2 rounded-lg text-sm cursor-pointer border" style="border-color: var(--accent); color: var(--accent); background: var(--bg2);">
		🔄 Reload providers.json
	</button>
	{#if reloadMsg}<span class="ml-3 text-sm font-semibold" style="color: var(--green);">{reloadMsg}</span>{/if}

	<div class="rounded-xl border overflow-hidden" style="background: var(--bg2); border-color: var(--border);">
		<table class="w-full text-sm">
			<thead><tr style="background: var(--bg3);">
				<th class="text-left px-4 py-2 text-xs" style="color: var(--text2);">Model ID</th>
				<th class="text-left px-4 py-2 text-xs" style="color: var(--text2);">Provider</th>
			</tr></thead>
			<tbody>
				{#each models as m}
					<tr class="border-t" style="border-color: var(--border);">
						<td class="px-4 py-2 font-mono text-xs" style="color: var(--accent);">{m.id}</td>
						<td class="px-4 py-2">{m.owned_by}</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
</div>

</div>
